# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ezClocker' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ezClocker
  pod 'Mixpanel'
  pod 'Firebase/Core'
  pod 'Firebase/Crashlytics'
  pod 'GooglePlaces', '~> 3.3.0'
  pod 'GoogleMaps', '~> 3.3.0'
  pod 'Amplitude', '~> 7.2.0'
end

target 'ezClocker Kiosk' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for ezClocker
    pod 'Mixpanel'
    pod 'Firebase/Core'
    pod 'Firebase/Crashlytics'
    pod 'GooglePlaces', '~> 3.3.0'
    pod 'GoogleMaps', '~> 3.3.0'
    pod 'Amplitude', '~> 7.2.0'
    
end

target 'ezClocker Personal' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ezClocker Personal
  pod 'Firebase/Core'
  pod 'Mixpanel'
  pod 'Firebase/Crashlytics'
  pod 'Amplitude', '~> 7.2.0'
end
